//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDP4500
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UsuariosDBEntities : DbContext
    {
        public UsuariosDBEntities()
            : base("name=UsuariosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<MARCACION> MARCACION { get; set; }
        public virtual DbSet<REGISTRO> REGISTRO { get; set; }
        public virtual DbSet<TIPOMARCACION> TIPOMARCACION { get; set; }
    
        public virtual ObjectResult<mostrarRegistros_Result> mostrarRegistros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mostrarRegistros_Result>("mostrarRegistros");
        }
    }
}
